version: '3'
services:
  compiler:
    build:
      context: .
      dockerfile: Dockerfiles/compiler.Dockerfile
    volumes:
      - .:/workdir
      - /workdir/node_modules
    working_dir: /workdir
    entrypoint: ./entrypoint.sh
  clasp:
    build:
      context: .
      dockerfile: Dockerfiles/clasp.Dockerfile
    volumes:
      - ./.clasprc.json:/root/.clasprc.json
      - .:/workdir
    working_dir: /workdir
    entrypoint: ./entrypoint.sh
