# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo_output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo_output
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A second hello"
      - attach_workspace:
          at: my_workspace
      - run: |
          cat my_workspace/echo_output
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
  
